// This file is auto-generated by @hey-api/openapi-ts

export const AuthorSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: 'author_1'
        },
        username: {
            type: 'string',
            example: 'lesha_krid'
        },
        displayName: {
            type: 'string',
            example: 'Леша Крид'
        },
        avatarUrl: {
            type: 'string',
            format: 'uri',
            example: 'https://s3.regru.cloud/mecenate-test-picture/logo1.webm'
        },
        bio: {
            type: 'string',
            example: 'Музыка, визуальное искусство и эксперименты.'
        },
        subscribersCount: {
            type: 'integer',
            example: 1420
        },
        isVerified: {
            type: 'boolean',
            example: true
        }
    }
} as const;

export const PostSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: 'post_1'
        },
        author: {
            $ref: '#/components/schemas/Author'
        },
        title: {
            type: 'string',
            example: 'Подготовка к лету'
        },
        body: {
            type: 'string',
            description: 'Full text. Empty string for paid posts.'
        },
        preview: {
            type: 'string',
            description: 'Short preview up to 120 chars'
        },
        coverUrl: {
            type: 'string',
            format: 'uri',
            example: 'https://s3.regru.cloud/mecenate-test-picture/pic1.jpeg'
        },
        likesCount: {
            type: 'integer',
            example: 248
        },
        commentsCount: {
            type: 'integer',
            example: 17
        },
        isLiked: {
            type: 'boolean',
            description: 'Whether current user liked this post'
        },
        tier: {
            type: 'string',
            enum: [
                'free',
                'paid'
            ]
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const CommentSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: 'comment_1'
        },
        postId: {
            type: 'string',
            example: 'post_1'
        },
        author: {
            $ref: '#/components/schemas/Author'
        },
        text: {
            type: 'string',
            example: 'Очень круто, ждём продолжения!'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const PostsResponseSchema = {
    type: 'object',
    properties: {
        ok: {
            type: 'boolean',
            example: true
        },
        data: {
            type: 'object',
            properties: {
                posts: {
                    type: 'array',
                    items: {
                        $ref: '#/components/schemas/Post'
                    }
                },
                nextCursor: {
                    type: 'string',
                    nullable: true,
                    example: 'post_10'
                },
                hasMore: {
                    type: 'boolean'
                }
            }
        }
    }
} as const;

export const PostDetailResponseSchema = {
    type: 'object',
    properties: {
        ok: {
            type: 'boolean',
            example: true
        },
        data: {
            type: 'object',
            properties: {
                post: {
                    $ref: '#/components/schemas/Post'
                }
            }
        }
    }
} as const;

export const LikeResponseSchema = {
    type: 'object',
    properties: {
        ok: {
            type: 'boolean',
            example: true
        },
        data: {
            type: 'object',
            properties: {
                isLiked: {
                    type: 'boolean'
                },
                likesCount: {
                    type: 'integer'
                }
            }
        }
    }
} as const;

export const CommentsResponseSchema = {
    type: 'object',
    properties: {
        ok: {
            type: 'boolean',
            example: true
        },
        data: {
            type: 'object',
            properties: {
                comments: {
                    type: 'array',
                    items: {
                        $ref: '#/components/schemas/Comment'
                    }
                },
                nextCursor: {
                    type: 'string',
                    nullable: true
                },
                hasMore: {
                    type: 'boolean'
                }
            }
        }
    }
} as const;

export const CommentCreatedResponseSchema = {
    type: 'object',
    properties: {
        ok: {
            type: 'boolean',
            example: true
        },
        data: {
            type: 'object',
            properties: {
                comment: {
                    $ref: '#/components/schemas/Comment'
                }
            }
        }
    }
} as const;

export const ErrorResponseSchema = {
    type: 'object',
    properties: {
        ok: {
            type: 'boolean',
            example: false
        },
        error: {
            type: 'object',
            properties: {
                code: {
                    type: 'string',
                    example: 'NOT_FOUND'
                },
                message: {
                    type: 'string',
                    example: 'Post not found'
                }
            }
        }
    }
} as const;
