// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetPostsByIdCommentsData, GetPostsByIdCommentsErrors, GetPostsByIdCommentsResponses, GetPostsByIdData, GetPostsByIdErrors, GetPostsByIdResponses, GetPostsData, GetPostsErrors, GetPostsResponses, PostPostsByIdCommentsData, PostPostsByIdCommentsErrors, PostPostsByIdCommentsResponses, PostPostsByIdLikeData, PostPostsByIdLikeErrors, PostPostsByIdLikeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get posts feed
 *
 * Paginated list of posts sorted by createdAt desc. Paid posts have empty body.
 */
export const getPosts = <ThrowOnError extends boolean = false>(options?: Options<GetPostsData, ThrowOnError>) => (options?.client ?? client).get<GetPostsResponses, GetPostsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts',
    ...options
});

/**
 * Get post by ID
 *
 * Full post details. Paid posts have empty body.
 */
export const getPostsById = <ThrowOnError extends boolean = false>(options: Options<GetPostsByIdData, ThrowOnError>) => (options.client ?? client).get<GetPostsByIdResponses, GetPostsByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts/{id}',
    ...options
});

/**
 * Toggle like
 *
 * Like/unlike a post (toggle). Triggers a like_updated WebSocket event after 1-3s delay.
 */
export const postPostsByIdLike = <ThrowOnError extends boolean = false>(options: Options<PostPostsByIdLikeData, ThrowOnError>) => (options.client ?? client).post<PostPostsByIdLikeResponses, PostPostsByIdLikeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts/{id}/like',
    ...options
});

/**
 * Get comments
 *
 * Paginated list of comments for a post.
 */
export const getPostsByIdComments = <ThrowOnError extends boolean = false>(options: Options<GetPostsByIdCommentsData, ThrowOnError>) => (options.client ?? client).get<GetPostsByIdCommentsResponses, GetPostsByIdCommentsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts/{id}/comments',
    ...options
});

/**
 * Add comment
 *
 * Create a new comment. Triggers a comment_added WebSocket event.
 */
export const postPostsByIdComments = <ThrowOnError extends boolean = false>(options: Options<PostPostsByIdCommentsData, ThrowOnError>) => (options.client ?? client).post<PostPostsByIdCommentsResponses, PostPostsByIdCommentsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/posts/{id}/comments',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
