// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://k8s.mectest.ru/test-app' | (string & {});
};

export type Author = {
    id?: string;
    username?: string;
    displayName?: string;
    avatarUrl?: string;
    bio?: string;
    subscribersCount?: number;
    isVerified?: boolean;
};

export type Post = {
    id?: string;
    author?: Author;
    title?: string;
    /**
     * Full text. Empty string for paid posts.
     */
    body?: string;
    /**
     * Short preview up to 120 chars
     */
    preview?: string;
    coverUrl?: string;
    likesCount?: number;
    commentsCount?: number;
    /**
     * Whether current user liked this post
     */
    isLiked?: boolean;
    tier?: 'free' | 'paid';
    createdAt?: string;
};

export type Comment = {
    id?: string;
    postId?: string;
    author?: Author;
    text?: string;
    createdAt?: string;
};

export type PostsResponse = {
    ok?: boolean;
    data?: {
        posts?: Post[];
        nextCursor?: string | null;
        hasMore?: boolean;
    };
};

export type PostDetailResponse = {
    ok?: boolean;
    data?: {
        post?: Post;
    };
};

export type LikeResponse = {
    ok?: boolean;
    data?: {
        isLiked?: boolean;
        likesCount?: number;
    };
};

export type CommentsResponse = {
    ok?: boolean;
    data?: {
        comments?: Comment[];
        nextCursor?: string | null;
        hasMore?: boolean;
    };
};

export type CommentCreatedResponse = {
    ok?: boolean;
    data?: {
        comment?: Comment;
    };
};

export type ErrorResponse = {
    ok?: boolean;
    error?: {
        code?: string;
        message?: string;
    };
};

export type GetPostsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of posts (max 20)
         */
        limit?: number;
        /**
         * ID of the last received post
         */
        cursor?: string;
        /**
         * Filter by tier: free or paid
         */
        tier?: 'free' | 'paid';
        /**
         * Return 500 for error handling testing
         */
        simulate_error?: boolean;
    };
    url: '/posts';
};

export type GetPostsErrors = {
    /**
     * Invalid or missing UUID token
     */
    401: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetPostsError = GetPostsErrors[keyof GetPostsErrors];

export type GetPostsResponses = {
    /**
     * Posts list
     */
    200: PostsResponse;
};

export type GetPostsResponse = GetPostsResponses[keyof GetPostsResponses];

export type GetPostsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/posts/{id}';
};

export type GetPostsByIdErrors = {
    /**
     * Invalid or missing UUID token
     */
    401: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetPostsByIdError = GetPostsByIdErrors[keyof GetPostsByIdErrors];

export type GetPostsByIdResponses = {
    /**
     * Post detail
     */
    200: PostDetailResponse;
};

export type GetPostsByIdResponse = GetPostsByIdResponses[keyof GetPostsByIdResponses];

export type PostPostsByIdLikeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/posts/{id}/like';
};

export type PostPostsByIdLikeErrors = {
    /**
     * Invalid or missing UUID token
     */
    401: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type PostPostsByIdLikeError = PostPostsByIdLikeErrors[keyof PostPostsByIdLikeErrors];

export type PostPostsByIdLikeResponses = {
    /**
     * Like toggled
     */
    200: LikeResponse;
};

export type PostPostsByIdLikeResponse = PostPostsByIdLikeResponses[keyof PostPostsByIdLikeResponses];

export type GetPostsByIdCommentsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        /**
         * Number of comments
         */
        limit?: number;
        /**
         * Cursor for pagination
         */
        cursor?: string;
    };
    url: '/posts/{id}/comments';
};

export type GetPostsByIdCommentsErrors = {
    /**
     * Invalid or missing UUID token
     */
    401: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetPostsByIdCommentsError = GetPostsByIdCommentsErrors[keyof GetPostsByIdCommentsErrors];

export type GetPostsByIdCommentsResponses = {
    /**
     * Comments list
     */
    200: CommentsResponse;
};

export type GetPostsByIdCommentsResponse = GetPostsByIdCommentsResponses[keyof GetPostsByIdCommentsResponses];

export type PostPostsByIdCommentsData = {
    body: {
        text: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/posts/{id}/comments';
};

export type PostPostsByIdCommentsErrors = {
    /**
     * Request body validation failed
     */
    400: ErrorResponse;
    /**
     * Invalid or missing UUID token
     */
    401: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type PostPostsByIdCommentsError = PostPostsByIdCommentsErrors[keyof PostPostsByIdCommentsErrors];

export type PostPostsByIdCommentsResponses = {
    /**
     * Comment created
     */
    201: CommentCreatedResponse;
};

export type PostPostsByIdCommentsResponse = PostPostsByIdCommentsResponses[keyof PostPostsByIdCommentsResponses];
